Fix aeson v2 api breakage in JWTInteropTests
Since aeson 2.0.0.0 (~2021), its KeyMap is indexed by separate type Key
-- no longer by Text.

This commit then fixes typecheck error in tests:

> tests/src/Web/JWTInteropTests.hs:59:38: error: [GHC-83865]
>     • Couldn't match expected type ‘Key’ with actual type ‘T.Text’
>     • In the first argument of ‘key’, namely ‘key'’
>       In the second argument of ‘(^?)’, namely ‘key key'’
>       In the expression: toJSON claims' ^? key key'
>    |
> 59 |     let json = toJSON claims' ^? key key'
>    |                                      ^^^^

And correspondignly, the test can no longer build with aeson-v1; thus
the version requirement bump.